require("core.plugin_config.lazy")
require("core.plugin_config.mason")
require("core.plugin_config.oil")
require("core.plugin_config.nvim-treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.nvim-web-devicons")
